spring.application.name=jichulmate

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

#?? ?? ??
server.port=8081

# =========================
# Oracle DB ?? ??
# =========================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=???? <- ??? ? (Orcale ??)
spring.datasource.password=???? <- ??? ? (Orcale ??)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# =========================
# JPA ??
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# JSP / ?? ?? ???
# =========================
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# =========================
# Mail - ?? euna ??
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ddd041128@gmail.com
spring.mail.password=hpcagvsfzcuguyzg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true